# Generated by Django 5.2.6 on 2025-09-17 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'item'], name='catalog_use_user_id_028d08_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['liked'], name='catalog_use_liked_be99de_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['bookmarked'], name='catalog_use_bookmar_f5984a_idx'),
        ),
        migrations.AddField(
            model_name='item',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authored_items', to='catalog.person'),
        ),
        migrations.AddField(
            model_name='item',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_items', to='catalog.person'),
        ),
        migrations.AddField(
            model_name='item',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='produced_items', to='catalog.person'),
        ),
    ]
